name: smart_file_manager
description: A smart file management system app built using Flutter and Dart.
publish_to: "none" # since it's not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI and utility
  cupertino_icons: ^1.0.6
  intl: ^0.20.2

  # State Management (REQUIRED by home_screen.dart)
  provider: ^6.0.5

  # File Operations
  file_picker: ^10.3.3
  open_filex: ^4.3.4
  path_provider: ^2.1.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # The assets folder reference (Ensure you create the 'assets' directory if it's needed)
  assets:
    - assets/
